In [1]:
import pandas as pd
# import numpy as np
# import seaborn as sns
# import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("D:/! Моє навчання/мої проєкти/project 2 GoIT -/survey_results_public.csv", low_memory=False)
df_sch = pd.read_csv("D:/! Моє навчання/мої проєкти/project 2 GoIT -/survey_results_schema.csv")

Завдання 1. Підрахунок загальної кількості респондентів

In [3]:
respondents_count = df.shape[0]

print(f"Загальна кількість респондентів, які взяли участь в опитуванні: {respondents_count}")

Загальна кількість респондентів, які взяли участь в опитуванні: 49191

In [4]:
df_sch

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [5]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Завдання 2. Аналіз повноти відповідей респондентів

In [6]:
# знаходжу множити унікальних значень в кожній таблиці
schema_questions = set(df_sch['qname'])
main_columns = set(df.columns)

questions = list(schema_questions.intersection(main_columns)) # перетин (ті назви, що є в обох файлах)

full_responses_df = df[questions].dropna() # Фільтрую основний датафрейм за цими колонками та видаляємо рядки, де є хоча б один пропуск

perfect_respondents_count = full_responses_df.shape[0] # рахую кількість таких респондентів

print(f"Кількість респондентів, які відповіли на всі запитання: {perfect_respondents_count}")

Кількість респондентів, які відповіли на всі запитання: 0

In [7]:
# перевіряю себе, бо бентежить 0 в попередньому завданні
test_count = df[questions[:5]].dropna().shape[0]
print(f"Кількість людей, що відповіли на перші 5 питань: {test_count}")

Кількість людей, що відповіли на перші 5 питань: 835

In [8]:
df_sch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

In [9]:
#хочу перевірити тип колонки WorkExp
# df.info() не показує потрібну інформацію
df.iloc[:, :7].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ResponseId      49191 non-null  int64
 1   MainBranch      49191 non-null  object
 2   Age             49191 non-null  object
 3   EdLevel         48149 non-null  object
 4   Employment      48339 non-null  object
 5   EmploymentAddl  44875 non-null  object
 6   WorkExp         42893 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 2.6+ MB

Завдання 3. Статистичний аналіз досвіду респондентів (WorkExp)

In [10]:
cleaned_work_exp=df['WorkExp'].dropna() # очищаю колонку від пропущених значень

mean_val = round(cleaned_work_exp.mean(), 2)
median_val = cleaned_work_exp.median()
mode_val = cleaned_work_exp.mode()[0]  # витягую перше значення з результату mode

work_exp_stats = pd.Series({
    'Mean': mean_val,
    'Median': median_val,
    'Mode': mode_val})

work_exp_stats

Mean      13.37
Median    10.00
Mode      10.00
dtype: float64

Завдання 4. Аналіз віддаленої роботи

In [11]:
# Шукаю необхідну колонку: - RemoteWork
df.iloc[:, :16].info() #або list(df.columns) - цей не такий інформативний

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ResponseId       49191 non-null  int64
 1   MainBranch       49191 non-null  object
 2   Age              49191 non-null  object
 3   EdLevel          48149 non-null  object
 4   Employment       48339 non-null  object
 5   EmploymentAddl   44875 non-null  object
 6   WorkExp          42893 non-null  float64
 7   LearnCodeChoose  46858 non-null  object
 8   LearnCode        33556 non-null  object
 9   LearnCodeAI      45201 non-null  object
 10  AILearnHow       28257 non-null  object
 11  YearsCode        43042 non-null  float64
 12  DevType          43680 non-null  object
 13  OrgSize          34178 non-null  object
 14  ICorPM           33243 non-null  object
 15  RemoteWork       33780 non-null  object
dtypes: float64(2), int64(1), object(13)
memory usage: 6.0+ MB

In [12]:
df['RemoteWork'].unique() #шукаю унікальні значення роботи - є Remote

array(['Remote', 'Hybrid (some in-person, leans heavy to flexibility)',
       nan, 'In-person', 'Hybrid (some remote, leans heavy to in-person)',
       'Your choice (very flexible, you can come in when you want or just as needed)'],
      dtype=object)

In [13]:
remote_workers = df[df['RemoteWork'] == 'Remote'] #фільтрую тих, хто працює відділено

remote_count = remote_workers.shape[0] #рахую кількість
print(f"Кількість респондентів, які працюють віддалено: {remote_count}")

Кількість респондентів, які працюють віддалено: 10931

Завдання 5. Визначення популярності Python

In [14]:
# шукаю назву колонки, що містить мови
languages_col = [col for col in df.columns if 'Language' in col]
print(languages_col) #'LanguageHaveWorkedWith'

['LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry']

In [15]:
df['LanguageHaveWorkedWith'].unique() #шукаю унікальні значення в стовпцю

array(['Bash/Shell (all shells);Dart;SQL', 'Java',
       'Dart;HTML/CSS;JavaScript;TypeScript', ...,
       'Bash/Shell (all shells);C#;C++;GDScript;HTML/CSS;JavaScript;Python;Rust;SQL;Zig;Mojo;Gleam',
       'Bash/Shell (all shells);HTML/CSS;Lisp;PowerShell;Python',
       'Assembly;C#;Go;Java;JavaScript;Rust'],
      shape=(15479,), dtype=object)

lang_column = 'LanguageHaveWorkedWith'

python_users_mask = df[lang_column].str.contains('Python', na=False) # na=False - для ігнорування порожніх значень

python_count = python_users_mask.sum() #18466

total_respondents = len(df)

python_percentage = (python_count / total_respondents) * 100 # відсоток
print(f"Відсоток респондентів, які програмують на Python: {python_percentage:.1f}%")

In [19]:
lang_column = 'LanguageHaveWorkedWith'
total_respondents = len(df)

python_users_mask2 = df[lang_column].str.contains(r'\bPython\b', na=False)
python_count2 = python_users_mask2.sum() #18410
python_percentage2 = (python_count2 / total_respondents) * 100
print(f"Відсоток респондентів, які програмують на Python: {python_percentage2:.1f}%")
#Я вважаю, цей результат буде більш точний від попереднього, оскільки за допомогою \b ми уникаємо уникнути помилкового підрахунку схожих назв (їх 55 штук)

Відсоток респондентів, які програмують на Python: 37.4%

Завдання 6. Аналіз шляхів навчання програмуванню

In [20]:
learn_cols = [col for col in df.columns if 'Learn' in col] # шукаю колонку зі способами навчання
print(learn_cols)

['LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow']

In [21]:
print(df['LearnCode'].unique()[:10])

['Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)'
 'Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange'
 'Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);Technical documentation (is generated for/by the tool or system)'
 'Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps'
 nan
 'Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Colleague or on-the-job training;Blogs or podcasts'
 'Videos (not associated with specific online course or certification);AI CodeGen tools or AI-enabled apps;Blogs or podcasts'
 'Books / Physical media;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Blogs or podcasts'
 'Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Blogs or podcasts'
 'Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);Blogs or podcasts']

In [22]:
learn_col = 'LearnCode'
search_phrase = 'Online Courses'

online_learners_mask = df[learn_col].str.contains(search_phrase, na=False)
online_count = online_learners_mask.sum()

print(f"Кількість респондентів, які навчалися програмувати через онлайн курси: {online_count}")

Кількість респондентів, які навчалися програмувати через онлайн курси: 10973

Завдання 7. Географічний аналіз компенсації Python-розробників

In [23]:
python_df = df[python_users_mask2].copy() #використала вже готову комірку з 5 завдання
country_comp = python_df.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])
country_comp = country_comp.dropna(how='all')
country_comp.columns = ['Середня компенсація', 'Медіанна компенсація']
result_df = round(country_comp.sort_values(by='Медіанна компенсація', ascending=False)) #сортую за медіаною, бо вона показує точнішу "картину"
result_df

                          Середня компенсація  Медіанна компенсація
Country
Oman                                 390135.0              390135.0
Andorra                              226104.0              226104.0
United States of America             173275.0              150000.0
Israel                               135828.0              142594.0
Switzerland                          156738.0              142592.0
...                                       ...                   ...
Cambodia                               1270.0                1270.0
Afghanistan                           22329.0                1000.0
Togo                                    354.0                 354.0
Palestine                                78.0                  78.0
Antigua and Barbuda                       1.0                   1.0

[153 rows x 2 columns]

In [24]:
result_df.loc['Ukraine'] #цікаво дізнатись для України

Середня компенсація     34001.0
Медіанна компенсація    25660.0
Name: Ukraine, dtype: float64

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [25]:
# 1. Сортуємо весь датафрейм за колонкою компенсації у спадному порядку
# Використовуємо .sort_values з параметром ascending=False
top_paid_df = df.sort_values(by='ConvertedCompYearly', ascending=False)

# 2. Вибираємо топ-5 респондентів та лише колонку з освітою ('EdLevel')
# Використовуємо .head(5) для вибірки перших п'яти записів
top_5_education = top_paid_df[['ConvertedCompYearly', 'EdLevel']].head(5)

# 3. Виводимо результат
top_5_education

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

Завдання 9. Аналіз популярності Python по віковим категоріям

In [26]:
age_total = df.groupby('Age').size()

python_respondents = df[python_users_mask2]

age_python = python_respondents.groupby('Age').size()

age_python_pct = (age_python / age_total * 100).fillna(0) #.fillna(0) на випадок, якщо в віковій категорії не виявиться Python-розробників

age_analysis_df = age_python_pct.reset_index()
age_analysis_df.columns = ['Вікова категорія', 'Відсоток Python-розробників']

age_analysis_df['Відсоток Python-розробників'] = age_analysis_df['Відсоток Python-розробників'].round(1)
age_analysis_df

    Вікова категорія  Відсоток Python-розробників
0    18-24 years old                         39.9
1    25-34 years old                         36.8
2    35-44 years old                         36.6
3    45-54 years old                         38.5
4    55-64 years old                         37.2
5  65 years or older                         31.3
6  Prefer not to say                         31.0

Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [27]:
salary_threshold = df['ConvertedCompYearly'].quantile(0.75) #поріг, вище якого знаходяться 25% найбільш оплачуваних розробників

high_paid_remote_mask = (df['ConvertedCompYearly'] > salary_threshold) & \
                        (df['RemoteWork'].str.contains('Remote', na=False))

remote_pros_df = df[high_paid_remote_mask].copy()

industry_stats = remote_pros_df['Industry'].value_counts() # .value_counts() автоматично сортує за частотою (від найбільш до найменш поширених)

top_industries = industry_stats.reset_index()
top_industries.columns = ['Індустрія', 'Кількість спеціалістів']

top_industries.head(10)

                                    Індустрія  Кількість спеціалістів
0                        Software Development                    1186
1                                     Fintech                     190
2                                  Healthcare                     188
3                                      Other:                     176
4  Internet, Telecomm or Information Services                     138
5                  Banking/Financial Services                      88
6                                  Government                      78
7                Media & Advertising Services                      75
8                Retail and Consumer Services                      65
9             Transportation, or Supply Chain                      63